version: '3.4'

networks:
  default:
    external:
      name: apps

services:

  uf1:
    image: local/universalforwarder:8.1.3
    build:
      context: ../.images/splunk
      network: host
      args:
        VERSION: 8.1.3
        TOOL: universalforwarder
    container_name: uf1
    hostname: uf1
    environment:
      LANG: en_US.utf8
      SPLUNK_ROLE: splunk_universal_forwarder
      SPLUNK_START_ARGS: --accept-license
      SPLUNK_INDEXER_URL: sbs
      SPLUNK_PASSWORD: password
      SPLUNK_CLUSTER_MASTER_URL: cm1
      SPLUNK_IDXC_DISCOVERYPASS4SYMMKEY: cm_and_forwarder_comms
    volumes:
    - ${HOME}/projects:/projects
